name: build-macos
on:
  push:
    tags: ["v*"]
    branches:
      - check/ci

jobs:
  build-sign-notarize:
    runs-on: macos-15

    steps:
    - uses: actions/checkout@v4

    # Import certificates into Keychain
    - uses: apple-actions/import-codesign-certs@v3
      with:
        p12-file-base64: ${{ secrets.DEV_ID_CERT_P12 }}
        p12-password:    ${{ secrets.DEV_ID_CERT_PASSWORD }}

    #  Xcode build (signed)
    - name: Build release
      run: |
        xcodebuild -project QuickShelf.xcodeproj \
                   -scheme QuickShelf \
                   -config Release \
                   -archivePath build/QuickShelf.xcarchive \
                   clean archive \
                   CODE_SIGN_IDENTITY="" \
                   CODE_SIGNING_REQUIRED="NO"
      env:
        TEAM_ID: ${{ secrets.TEAM_ID }}

    - name: Codesign
      run: |
        xcrun codesign --force --deep \
          --timestamp \
          --options runtime \
          --sign "$SIGN_ID" "build/QuickShelf.xcarchive/Products/Applications/QuickShelf.app"
      env:
        TEAM_ID: ${{ secrets.TEAM_ID }}
        SIGN_ID: ${{ secrets.DEVID_COMMON_NAME }}
    # ZIP the .app
    - name: Zip app
      run: |
        ditto -c -k --keepParent "build/QuickShelf.xcarchive/Products/Applications/QuickShelf.app" QuickShelf.zip

    # Submit with notarytool (save Keychain profile on the fly)
    - name: Store notary credentials
      run: |
        xcrun notarytool store-credentials "notary-profile" \
          --apple-id "$APPLE_ID" \
          --team-id "$TEAM_ID" \
          --password "$APPLE_PASS"
      env:
        APPLE_ID: ${{ secrets.APPLE_ID }}
        APPLE_PASS: ${{ secrets.APPLE_PASS }}
        TEAM_ID: ${{ secrets.TEAM_ID }}

    - name: Submit to notarization
      run: |
        xcrun notarytool submit QuickShelf.zip \
          --keychain-profile "notary-profile" --wait

    # Staple
    - name: Staple ticket
      run: xcrun stapler staple "build/QuickShelf.xcarchive/Products/Applications/QuickShelf.app"

    # Gatekeeper verification and re-zipping
    - name: Validate
      run: |
        spctl --assess --type execute --verbose=4 "build/QuickShelf.xcarchive/Products/Applications/QuickShelf.app"
        xcrun stapler validate "build/QuickShelf.xcarchive/Products/Applications/QuickShelf.app"
        ditto -c -k --keepParent "build/QuickShelf.xcarchive/Products/Applications/QuickShelf.app" QuickShelf.zip

    # Upload Deliverables
    - uses: actions/upload-artifact@v4
      with:
        name: QuickShelf-macOS
        path: QuickShelf.zip
